//! Registered command specs (68), transcribed from the oracle's
//! `src/command_catalog/data.rs` via its own export (contracts/golden/catalog.json).
//! Order is load-bearing: `/help` and the README table render in this order.
const c = @import("catalog.zig");

pub const CommandKey = enum {
    help,
    persona_route,
    persona_ask,
    roleplay,
    whois,
    profile,
    ask_message,
    perms,
    modcall,
    server_blueprint,
    server_create_channel,
    server_rename_channel,
    server_slowmode,
    server_delete_channel,
    server_assign_role,
    server_remove_role,
    server_move_member,
    server_purge,
    webhook,
    forum_draft,
    forum_post,
    forum_perms,
    remember,
    forget,
    pending_list,
    pending_confirm,
    pending_dismiss,
    recall,
    reputation,
    memory_menu,
    summarize,
    see,
    ocr,
    describe_image,
    read_image,
    stats,
    nsfw,
    admin_show,
    admin_persona,
    admin_learning,
    admin_nsfw,
    admin_vision,
    admin_cooldown,
    admin_act,
    admin_budget,
    admin_brain,
    admin_flush,
    admin_export,
    admin_reset,
    admin_dashboard,
    admin_quarantine,
    admin_contradict,
    admin_resolve,
    voice_consent,
    voice_notice,
    voice_play,
    voice_pause,
    voice_resume_music,
    voice_stop_music,
    voice_volume,
    voice_join,
    voice_resume,
    voice_leave,
    voice_status,
    voice_diagnostics,
    voice_mode,
    voice_verify_start,
    voice_verify_report,
};

pub const registered = [_]c.CommandSpec{
    .{ .key = .help, .kind = .slash, .name = "help", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .start, .description = "Browse commands available to you privately.", .private = true },
    .{ .key = .persona_route, .kind = .slash, .name = "persona route", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .conversation, .description = "Choose a persona and explain the routing.", .private = false },
    .{ .key = .persona_ask, .kind = .slash, .name = "persona ask", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c8, .section = .conversation, .description = "Ask a question through the configured generation backend.", .private = false },
    .{ .key = .roleplay, .kind = .slash, .name = "roleplay", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c8, .section = .conversation, .description = "Roleplay as Aviva in a DM or NSFW channel when the nsfw gate is on.", .private = false },
    .{ .key = .whois, .kind = .slash, .name = "whois", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .server, .description = "Read a member's profile and roles.", .private = false },
    .{ .key = .profile, .kind = .user_context, .name = "Abbey: profile", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .server, .description = "Read the selected member's profile privately.", .private = true },
    .{ .key = .ask_message, .kind = .message_context, .name = "Ask Abbey", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c8, .section = .conversation, .description = "Ask about a selected message privately.", .private = true },
    .{ .key = .perms, .kind = .slash, .name = "perms", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .server, .description = "Explain a member's channel permissions.", .private = false },
    .{ .key = .modcall, .kind = .slash, .name = "modcall", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .moderate_members }, .access = .a2, .condition = .c7, .section = .moderation, .description = "Recommend a moderation action after permission and hierarchy checks.", .private = true },
    .{ .key = .server_blueprint, .kind = .slash, .name = "server blueprint", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .server, .description = "Create a server blueprint without changing the server.", .private = true },
    .{ .key = .server_create_channel, .kind = .slash, .name = "server create-channel", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_channels }, .access = .a8, .condition = .c0, .section = .server, .description = "Create a text channel when you and Abbey both have Manage Channels.", .private = true },
    .{ .key = .server_rename_channel, .kind = .slash, .name = "server rename-channel", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_channels }, .access = .a8, .condition = .c0, .section = .server, .description = "Rename a channel when you and Abbey both have Manage Channels.", .private = true },
    .{ .key = .server_slowmode, .kind = .slash, .name = "server slowmode", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_channels }, .access = .a8, .condition = .c0, .section = .server, .description = "Set channel slowmode when you and Abbey both have Manage Channels.", .private = true },
    .{ .key = .server_delete_channel, .kind = .slash, .name = "server delete-channel", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_channels }, .access = .a8, .condition = .c0, .section = .server, .description = "Delete a channel with confirm:true when you and Abbey both have Manage Channels.", .private = true },
    .{ .key = .server_assign_role, .kind = .slash, .name = "server assign-role", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_roles }, .access = .a9, .condition = .c0, .section = .server, .description = "Assign a role when you and Abbey both have Manage Roles.", .private = true },
    .{ .key = .server_remove_role, .kind = .slash, .name = "server remove-role", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_roles }, .access = .a9, .condition = .c0, .section = .server, .description = "Remove a role when you and Abbey both have Manage Roles.", .private = true },
    .{ .key = .server_move_member, .kind = .slash, .name = "server move-member", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .move_members }, .access = .a10, .condition = .c0, .section = .server, .description = "Move a member in voice when you and Abbey both have Move Members.", .private = true },
    .{ .key = .server_purge, .kind = .slash, .name = "server purge", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_messages }, .access = .a11, .condition = .c0, .section = .server, .description = "Purge recent messages with confirm:true when you and Abbey both have Manage Messages.", .private = true },
    .{ .key = .webhook, .kind = .slash, .name = "webhook", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_webhooks }, .access = .a3, .condition = .c0, .section = .server, .description = "Show a safe incoming-webhook setup guide.", .private = true },
    .{ .key = .forum_draft, .kind = .slash, .name = "forum draft", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .server, .description = "Suggest #help tags and preview a first-post template.", .private = true },
    .{ .key = .forum_post, .kind = .slash, .name = "forum post", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .server, .description = "Create a #help forum thread with a first-post template.", .private = true },
    .{ .key = .forum_perms, .kind = .slash, .name = "forum perms", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .server, .description = "Snapshot and gap-fill Abbey's #help forum overwrite bits.", .private = true },
    .{ .key = .remember, .kind = .slash, .name = "remember", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a1, .condition = .c0, .section = .memory, .description = "Store a fact about yourself; moderators may choose a member.", .private = true },
    .{ .key = .forget, .kind = .slash, .name = "forget", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a1, .condition = .c0, .section = .memory, .description = "Remove a stored fact about yourself or an authorized member.", .private = true },
    .{ .key = .pending_list, .kind = .slash, .name = "pending list", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a1, .condition = .c0, .section = .memory, .description = "Review proposed fact replacements.", .private = true },
    .{ .key = .pending_confirm, .kind = .slash, .name = "pending confirm", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a1, .condition = .c0, .section = .memory, .description = "Apply an explicitly chosen fact replacement.", .private = true },
    .{ .key = .pending_dismiss, .kind = .slash, .name = "pending dismiss", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a1, .condition = .c0, .section = .memory, .description = "Dismiss a proposed replacement and keep both facts.", .private = true },
    .{ .key = .recall, .kind = .slash, .name = "recall", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a1, .condition = .c0, .section = .memory, .description = "Read your facts and standing, or an authorized member's.", .private = true },
    .{ .key = .reputation, .kind = .slash, .name = "reputation", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a1, .condition = .c0, .section = .memory, .description = "Read your standing privately; moderators may choose a member.", .private = true },
    .{ .key = .memory_menu, .kind = .user_context, .name = "Abbey: memory", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a1, .condition = .c0, .section = .memory, .description = "Read the selected member's bounded memory card privately.", .private = true },
    .{ .key = .summarize, .kind = .slash, .name = "summarize", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c1, .section = .conversation, .description = "Summarize the recent conversation through the backend.", .private = false },
    .{ .key = .see, .kind = .slash, .name = "see", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c3, .section = .images, .description = "Describe an image; an optional question also needs generation.", .private = false },
    .{ .key = .ocr, .kind = .slash, .name = "ocr", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c9, .section = .images, .description = "Read the text in an image.", .private = false },
    .{ .key = .describe_image, .kind = .message_context, .name = "Abbey: describe image", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c2, .section = .images, .description = "Describe the first supported attachment privately.", .private = true },
    .{ .key = .read_image, .kind = .message_context, .name = "Abbey: read image text", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c9, .section = .images, .description = "Read text from the first supported attachment privately.", .private = true },
    .{ .key = .stats, .kind = .slash, .name = "stats", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .start, .description = "Read this conversation’s learning and reply budget.", .private = true },
    .{ .key = .nsfw, .kind = .slash, .name = "nsfw", .registration = .{ .contexts = &c.both_contexts, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .conversation, .description = "Enable or disable Aviva roleplay in this DM (in a server use /admin nsfw).", .private = true },
    .{ .key = .admin_show, .kind = .slash, .name = "admin show", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Read this server's settings.", .private = true },
    .{ .key = .admin_persona, .kind = .slash, .name = "admin persona", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Set the server's default persona.", .private = true },
    .{ .key = .admin_learning, .kind = .slash, .name = "admin learning", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Control learning for this server.", .private = true },
    .{ .key = .admin_nsfw, .kind = .slash, .name = "admin nsfw", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Enable or disable Aviva roleplay for this server (NSFW channels only).", .private = true },
    .{ .key = .admin_vision, .kind = .slash, .name = "admin vision", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Control image understanding for this server.", .private = true },
    .{ .key = .admin_cooldown, .kind = .slash, .name = "admin cooldown", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Set the unsolicited reply cooldown.", .private = true },
    .{ .key = .admin_act, .kind = .slash, .name = "admin act", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Opt this server into unsolicited replies or turn them off.", .private = true },
    .{ .key = .admin_budget, .kind = .slash, .name = "admin budget", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Set the hourly unsolicited reply budget.", .private = true },
    .{ .key = .admin_brain, .kind = .slash, .name = "admin brain", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Inspect the learning policy and exploration setting.", .private = true },
    .{ .key = .admin_flush, .kind = .slash, .name = "admin flush", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Persist current state and report each result.", .private = true },
    .{ .key = .admin_export, .kind = .slash, .name = "admin export", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Export the server's brain snapshot privately.", .private = true },
    .{ .key = .admin_reset, .kind = .slash, .name = "admin reset", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Clear only this channel's transcript.", .private = true },
    .{ .key = .admin_dashboard, .kind = .slash, .name = "admin dashboard", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Open private administration controls.", .private = true },
    .{ .key = .admin_quarantine, .kind = .slash, .name = "admin quarantine", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Mark a member's stored fact as suspect for review.", .private = true },
    .{ .key = .admin_contradict, .kind = .slash, .name = "admin contradict", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Record that two of a member's stored facts contradict each other.", .private = true },
    .{ .key = .admin_resolve, .kind = .slash, .name = "admin resolve", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c0, .section = .administration, .description = "Close a memory review with a verdict.", .private = true },
    .{ .key = .voice_consent, .kind = .slash, .name = "voice consent", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a0, .condition = .c4, .section = .voice, .description = "Review, agree to, or withdraw your voice choice.", .private = true },
    .{ .key = .voice_notice, .kind = .slash, .name = "voice notice", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c4, .section = .voice, .description = "Publish the member voice consent controls.", .private = true },
    .{ .key = .voice_play, .kind = .slash, .name = "voice play", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a5, .condition = .c4, .section = .voice, .description = "Mirror Spotify/Music from this Mac into voice; manager + present in VC. Music ≠ listen consent.", .private = true },
    .{ .key = .voice_pause, .kind = .slash, .name = "voice pause", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a5, .condition = .c4, .section = .voice, .description = "Pause mirrored music and close tap capture; listen consent unchanged.", .private = true },
    .{ .key = .voice_resume_music, .kind = .slash, .name = "voice resume-music", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a5, .condition = .c4, .section = .voice, .description = "Resume mirrored music only; never renews listen consent.", .private = true },
    .{ .key = .voice_stop_music, .kind = .slash, .name = "voice stop-music", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a5, .condition = .c4, .section = .voice, .description = "Stop tap capture and mirrored playback; listen consent unchanged.", .private = true },
    .{ .key = .voice_volume, .kind = .slash, .name = "voice volume", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a5, .condition = .c4, .section = .voice, .description = "Set mirror volume 0–100; Abbey speech ducks music to ¼.", .private = true },
    .{ .key = .voice_join, .kind = .slash, .name = "voice join", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a5, .condition = .c5, .section = .voice, .description = "Start voice after every participant's saved agreement.", .private = true },
    .{ .key = .voice_resume, .kind = .slash, .name = "voice resume", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a5, .condition = .c5, .section = .voice, .description = "Resume voice after current participant consent checks.", .private = true },
    .{ .key = .voice_leave, .kind = .slash, .name = "voice leave", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a6, .condition = .c4, .section = .voice, .description = "Stop the current call immediately without deleting consent.", .private = true },
    .{ .key = .voice_status, .kind = .slash, .name = "voice status", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a0, .condition = .c0, .section = .voice, .description = "Read your privacy-bounded voice status.", .private = true },
    .{ .key = .voice_diagnostics, .kind = .slash, .name = "voice diagnostics", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c4, .section = .voice, .description = "Read private content-free operator voice diagnostics.", .private = true },
    .{ .key = .voice_mode, .kind = .slash, .name = "voice mode", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = .manage_server }, .access = .a4, .condition = .c4, .section = .voice, .description = "Read or select local/off voice mode (OpenAI Realtime removed).", .private = true },
    .{ .key = .voice_verify_start, .kind = .slash, .name = "voice verify start", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a7, .condition = .c6, .section = .voice, .description = "Arm a local content-free voice acceptance run.", .private = true },
    .{ .key = .voice_verify_report, .kind = .slash, .name = "voice verify report", .registration = .{ .contexts = &c.guild_only, .default_member_permissions = null }, .access = .a7, .condition = .c6, .section = .voice, .description = "Read the private local voice acceptance report.", .private = true },
};
