#!/usr/bin/env python3
"""Generate src/text/unicode_tables.zig from contracts/golden/unicode.json.

The JSON was dumped from Rust 1.98.0 core::char over every scalar value (see
contracts/golden/zig_golden_dump.rs.txt), so the Zig tables reproduce the
oracle's Unicode behavior exactly rather than approximating it.
`--check` fails when the committed file differs from a fresh render.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "contracts/golden/unicode.json"
# Case_Ignorable and Cased (non-ignorable) sets, probed from str::to_lowercase's
# final-sigma rule by contracts/golden/zig_golden_dump2.rs.txt.
CASING = ROOT / "contracts/golden/grounding.json"
TARGET = ROOT / "src/text/unicode_tables.zig"
PER_LINE = 6


def pairs(name, rows):
    out = [f"pub const {name} = [_][2]u21{{"]
    for i in range(0, len(rows), PER_LINE):
        chunk = rows[i:i + PER_LINE]
        out.append("    " + " ".join(f".{{ 0x{a:X}, 0x{b:X} }}," for a, b in chunk))
    out.append("};")
    return out


def render():
    data = json.loads(SOURCE.read_text())
    lines = [
        "//! GENERATED by tools/gen_unicode_tables.py from contracts/golden/unicode.json and grounding.json.",
        f"//! Rust 1.98.0 core::char tables, Unicode {'.'.join(str(x) for x in eval(data['unicode_version']))}. Do not edit.",
        "",
    ]
    for key, name in (("alphanumeric", "alphanumeric"), ("alphabetic", "alphabetic"),
                      ("uppercase", "uppercase"), ("whitespace", "whitespace")):
        lines += pairs(name, data[key])
        lines.append("")
    casing = json.loads(CASING.read_text())
    lines.append("/// Case_Ignorable, derived from Rust's final-sigma behavior.")
    lines += pairs("case_ignorable", casing["case_ignorable"])
    lines.append("")
    lines.append("/// Cased and not Case_Ignorable, derived the same way.")
    lines += pairs("cased", casing["cased"])
    lines.append("")
    lines += pairs("lowercase_map", data["lowercase_map"])
    lines.append("")
    multi = data["lowercase_multi"]
    lines.append("/// Scalar values whose lowercase form is longer than one scalar.")
    lines.append("pub const lowercase_multi = [_]struct { cp: u21, lower: []const u21 }{")
    for row in multi:
        lower = ", ".join(f"0x{x:X}" for x in row["lower"])
        lines.append(f"    .{{ .cp = 0x{row['cp']:X}, .lower = &.{{ {lower} }} }},")
    lines.append("};")
    raw = "\n".join(lines) + "\n"
    # Canonicalize through the pinned zig fmt so the gate's fmt stage and this
    # generator agree byte for byte.
    result = subprocess.run(["zig", "fmt", "--stdin"], input=raw.encode(), capture_output=True, check=True)
    return result.stdout.decode()


def main():
    text = render()
    if sys.argv[1:] == ["--check"]:
        if not TARGET.is_file() or TARGET.read_text() != text:
            print("unicode tables out of date: run tools/gen_unicode_tables.py", file=sys.stderr)
            return 1
        print(f"unicode tables: in sync ({TARGET.relative_to(ROOT)})")
        return 0
    TARGET.write_text(text)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
