#!/usr/bin/env python3
"""Text pin for the WDBX gateway installer and its launchd plist.

The installer talks to launchd (bootout, bootstrap, readiness verify), so it
cannot run under a test. What a test *can* hold still is the contract between
the plist's exec string and the installer's paths and rules: the episode
signing key the gateway signs every appended episode with is named by both,
generated by the installer, validated before bootstrap, and left in place by
--uninstall. Weaker than executing the transaction (deploy/test-install-launchd.py
does that for the bot installer); honest about it.
"""
import pathlib
import plistlib
import re
import unittest

HERE = pathlib.Path(__file__).resolve().parent
PLIST = HERE / "com.donaldfilimon.abbey-wdbx-gateway.plist"
INSTALLER = HERE / "install-wdbx-gateway-launchd.sh"
KEY_PATH = '"$HOME/.config/abbey-bot/episode-signing-key"'
EXPECTED_FLAGS = {
    "--grpc",
    "--events",
    "--store",
    "--token-file",
    "--episode-policy",
    "--episode-signing-key",
}


def exec_string() -> str:
    data = plistlib.loads(PLIST.read_bytes().replace(b"__HOME__", b"/Users/test"))
    args = data["ProgramArguments"]
    assert args[:2] == ["/bin/sh", "-c"], args
    return args[2]


def installer_text() -> str:
    return INSTALLER.read_text(encoding="utf-8")


class PlistContract(unittest.TestCase):
    def test_exec_string_carries_exactly_the_expected_flags(self):
        flags = set(re.findall(r"--[a-z-]+", exec_string()))
        self.assertEqual(flags, EXPECTED_FLAGS)

    def test_signing_key_flag_names_the_installer_path(self):
        self.assertIn(f"--episode-signing-key {KEY_PATH}", exec_string())
        self.assertIn(f"SIGNING_KEY_PATH={KEY_PATH}", installer_text())

    def test_signing_key_requires_the_policy_flag(self):
        # The gateway refuses a signing key without an episode policy.
        text = exec_string()
        self.assertLess(text.index("--episode-policy"), text.index("--episode-signing-key"))


class InstallerRules(unittest.TestCase):
    def setUp(self):
        self.text = installer_text()

    def test_generates_exactly_32_random_bytes_atomically(self):
        self.assertIn('head -c 32 /dev/urandom >"$SIGNING_KEY_PATH.new"', self.text)
        self.assertIn('chmod 600 "$SIGNING_KEY_PATH.new"', self.text)
        self.assertIn('mv -f "$SIGNING_KEY_PATH.new" "$SIGNING_KEY_PATH"', self.text)

    def test_validates_regular_file_mode_and_size(self):
        self.assertIn('[ -L "$SIGNING_KEY_PATH" ] || [ ! -f "$SIGNING_KEY_PATH" ]', self.text)
        self.assertIn('key_mode=$(stat -f \'%Lp\' "$SIGNING_KEY_PATH")', self.text)
        self.assertIn('[ "$key_mode" != "600" ]', self.text)
        self.assertIn('key_size=$(stat -f \'%z\' "$SIGNING_KEY_PATH")', self.text)
        self.assertIn('[ "$key_size" != "32" ]', self.text)

    def test_refuses_the_membership_key(self):
        self.assertIn('MEMBERSHIP_KEY="$STORE_DIR/gateway-membership/signing.key"', self.text)
        self.assertIn('cmp -s "$SIGNING_KEY_PATH" "$MEMBERSHIP_KEY"', self.text)

    def test_provisioning_precedes_bootstrap_and_follows_umask(self):
        umask = self.text.index("umask 077")
        generate = self.text.index("head -c 32 /dev/urandom")
        bootstrap = self.text.index('launchctl bootstrap "gui/$UID_NUM"')
        self.assertLess(umask, generate)
        self.assertLess(generate, bootstrap)

    def test_uninstall_leaves_the_key_in_place(self):
        start = self.text.index('if [ "$1" = "--uninstall" ]; then')
        end = self.text.index("exit 0", start)
        branch = self.text[start:end]
        self.assertNotIn("SIGNING_KEY_PATH", branch.replace("signing key left in place", ""))
        self.assertIn("signing key left in place", branch)

    def test_never_prints_key_bytes(self):
        for line in self.text.splitlines():
            if "SIGNING_KEY_PATH" in line and re.search(r"\b(cat|xxd|od|hexdump|base64)\b", line):
                self.fail(f"installer prints key material: {line}")


if __name__ == "__main__":
    unittest.main()
