#!/usr/bin/env python3
"""Prove every agent-instruction copy agrees with AGENTS.md, the canonical file.

AGENTS.md owns the rules. The other surfaces are derived from it:

- CLAUDE.md is exactly POINTER: a title and an `@AGENTS.md` import, never a copy.
- .cursor/agents/abbey-reviewer.md and .codex/agents/abbey-reviewer.toml carry
  the AGENTS.md `## Boundaries` body verbatim between BEGIN/END markers. The
  `.md` is where the reviewer-only text is edited; the `.toml` is rendered from
  it. The TOML is parsed with tomllib, so an invalid escape fails here rather
  than silently in an editor that loads the file.

`--write` regenerates the derived surfaces from AGENTS.md and the `.md` body;
without it the check only reads and fails on the first drift it finds.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
import tomllib

POINTER = "# CLAUDE.md\n\n@AGENTS.md\n\nSee AGENTS.md — canonical.\n"
BEGIN = "<!-- BEGIN AGENTS.md ## Boundaries (generated by scripts/check-instructions.py --write; edit AGENTS.md) -->"
END = "<!-- END AGENTS.md ## Boundaries -->"
CURSOR = pathlib.Path(".cursor/agents/abbey-reviewer.md")
CODEX = pathlib.Path(".codex/agents/abbey-reviewer.toml")


class Drift(Exception):
    """A derived instruction surface disagrees with its source."""


def read(path: pathlib.Path) -> str:
    # Text mode normalizes CRLF, so an autocrlf checkout (the Windows lane)
    # compares the same text as the macOS one.
    return path.read_text(encoding="utf-8")


def boundaries(agents: str) -> str:
    """The `## Boundaries` body: after its heading, up to the next `## ` heading."""
    lines = agents.split("\n")
    starts = [index for index, line in enumerate(lines) if line.rstrip() == "## Boundaries"]
    if len(starts) != 1:
        raise Drift(f"AGENTS.md must have exactly one '## Boundaries' heading, found {len(starts)}")
    body = []
    for line in lines[starts[0] + 1:]:
        if line.startswith("## "):
            break
        body.append(line)
    text = "\n".join(body).strip("\n")
    if not text:
        raise Drift("AGENTS.md '## Boundaries' section is empty")
    return text


def split_front_matter(markdown: str) -> tuple[dict[str, str], str]:
    lines = markdown.split("\n")
    if not lines or lines[0] != "---":
        raise Drift(f"{CURSOR} must open with '---' front matter")
    try:
        close = lines.index("---", 1)
    except ValueError:
        raise Drift(f"{CURSOR} front matter is not closed") from None
    fields = {}
    for line in lines[1:close]:
        key, separator, value = line.partition(":")
        if not separator or not key.strip():
            raise Drift(f"{CURSOR} front matter line is not 'key: value': {line!r}")
        fields[key.strip()] = value.strip()
    return fields, "\n".join(lines[close + 1:]).strip("\n")


def mirrored_block(body: str, source: str) -> str:
    if body.count(BEGIN) != 1 or body.count(END) != 1:
        raise Drift(f"{source} must contain the Boundaries BEGIN and END markers exactly once")
    start = body.index(BEGIN) + len(BEGIN)
    end = body.index(END)
    if end < start:
        raise Drift(f"{source} has the Boundaries END marker before BEGIN")
    return body[start:end].strip("\n")


def with_block(body: str, block: str) -> str:
    mirrored_block(body, str(CURSOR))  # marker shape is validated before rewriting
    start = body.index(BEGIN) + len(BEGIN)
    end = body.index(END)
    return body[:start] + "\n" + block + "\n" + body[end:]


def toml_basic(value: str) -> str:
    # A JSON string with ensure_ascii=False is a valid TOML basic string for
    # this text: both escape exactly backslash, quote and control characters.
    return json.dumps(value, ensure_ascii=False)


def toml_multiline(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"""', '""\\"')
    return '"""\n' + escaped + '"""'


def render_codex(fields: dict[str, str], body: str) -> str:
    return (
        f"name = {toml_basic(fields['name'])}\n"
        f"description = {toml_basic(fields['description'])}\n"
        f"developer_instructions = {toml_multiline(body)}\n"
    )


def check(root: pathlib.Path, write: bool = False) -> list[str]:
    """Return a list of drift messages (empty when every surface agrees)."""
    problems: list[str] = []
    agents = read(root / "AGENTS.md")
    block = boundaries(agents)

    claude = root / "CLAUDE.md"
    if not claude.exists() or read(claude) != POINTER:
        if write:
            claude.write_text(POINTER, encoding="utf-8")
        else:
            problems.append("CLAUDE.md must be exactly the AGENTS.md pointer (run --write)")

    cursor_text = read(root / CURSOR)
    fields, body = split_front_matter(cursor_text)
    missing = {"name", "description"} - fields.keys()
    if missing:
        raise Drift(f"{CURSOR} front matter lacks {sorted(missing)}")
    if mirrored_block(body, str(CURSOR)) != block:
        if write:
            body = with_block(body, block)
            head = cursor_text[: cursor_text.index("\n---", 3) + len("\n---")]
            (root / CURSOR).write_text(head + "\n\n" + body + "\n", encoding="utf-8")
        else:
            problems.append(f"{CURSOR}: Boundaries block differs from AGENTS.md (run --write)")

    codex_path = root / CODEX
    codex_text = read(codex_path) if codex_path.exists() else ""
    try:
        codex = tomllib.loads(codex_text)
    except tomllib.TOMLDecodeError as error:
        codex = None
        if not write:
            problems.append(f"{CODEX}: invalid TOML ({error})")
    expected = render_codex(fields, body)
    if codex is not None:
        for key, want in (("name", fields["name"]), ("description", fields["description"]),
                          ("developer_instructions", body)):
            if codex.get(key) != want and not write:
                problems.append(f"{CODEX}: {key} differs from {CURSOR} (run --write)")
        if not write and set(codex) != {"name", "description", "developer_instructions"}:
            problems.append(f"{CODEX}: unexpected keys {sorted(set(codex))}")
    if codex_text != expected:
        if write:
            codex_path.write_text(expected, encoding="utf-8")
        elif not problems:
            problems.append(f"{CODEX}: text differs from its rendered form (run --write)")
    if write:
        # Round trip: what was written must parse back to the same body.
        if tomllib.loads(read(codex_path))["developer_instructions"] != body:
            raise Drift(f"{CODEX}: rendered TOML does not round-trip")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=pathlib.Path, default=pathlib.Path(__file__).resolve().parents[1])
    parser.add_argument("--write", action="store_true", help="regenerate the derived surfaces")
    args = parser.parse_args()
    try:
        problems = check(args.root, write=args.write)
    except Drift as error:
        print(f"error: {error}")
        return 1
    for problem in problems:
        print(f"error: {problem}")
    if not problems:
        verb = "regenerated" if args.write else "agree with AGENTS.md"
        print(f"instruction surfaces {verb}: CLAUDE.md, {CURSOR}, {CODEX}")
    return int(bool(problems))


if __name__ == "__main__":
    sys.exit(main())
